include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    always_use_package_imports: false
    prefer_constructors_over_static_methods: false
    sort_pub_dependencies: false
    public_member_api_docs: false
    cascade_invocations: false
