name: steam_deals_application
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.2.0+1
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0
  mobx: ^2.2.0
  mobx_codegen: ^2.3.0
  flutter_mobx: ^2.0.6+5
  very_good_analysis: ^5.0.0+1
  vexana: ^3.4.3
  url_launcher: ^6.1.11
  connectivity_plus: ^2.3.5
  lottie: ^2.4.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
